### ISSUE TITLE
Bio moderation

### ISSUE THREAD

**Issue by JFreegman** [LittleVulpix/toxme#14]
It's recently come to my attention that people have been using bios to advertise their intent to participate in the sexual abuse of children. I'm not sure about the legal situation in regards to hosting these advertisements, but nonetheless, it reflects extremely poorly on our community, and I think there should be some automated way to handle them. This could be in the form of filtering, a flagging system etc.

Ideas and suggestions are welcome.

**Comment by LittleVulpix** [comment]
I support the idea. I don't really browse the friend list but checking it briefly it is indeed a bit of a tar pit. Unfortunately, I have a rather taxing real life job and I don't think I have time to manually inspect the users myself. Therefore, one of the three scenarios will happen:

1) (very likely) - I'll just disable bios. Prune them from the database + set any kind of call that stores or retrieves bios to an empty string so as not to break current toxme.io integrations.
2) (less likely, but could probably work) I will put in some kinda link that lets people flag a bad profile for review, and I'll review them in bulk whenever I get time
3) (even less likely, and I don't think it'll work), I'll ask people to report profiles they consider offensive to me directly
4) (not happening) I'll leave things as they are.

The problem with 2 is that it will require someone to flag the profiles, which requires some coding on my part... and I'm not much of a coder. Also requires time for me to review the submissions but that I can somewhat live with. Problem with 3 is just a lot of extra overhead for both the reportee and me.

Solution 1 resolves the issues with 2 and 3 but it also obviously takes away the possibility of having a bio altogether, so at that point you may as well just disable the "looking for friends" page because it'd all be a shot in the dark, which is also not ideal.

Lemme hear your thoughts.

**Comment by raingloom** [comment]
I think 1. is best as currently the majority of people using the bio feature seem to be pedophiles.

**Comment by LittleVulpix** [comment]
@raingloom fixed by #16
